source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.6"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Pg is the Ruby interface to the PostgreSQL RDBMS. It works with PostgreSQL 9.3 and later.
gem 'pg', '~> 1.5', '>= 1.5.3'

# Uglifier minifies JavaScript files by wrapping UglifyJS to be accessible in Ruby
gem 'uglifier', '~> 4.2'

#Flexible authentication solution for Rails with Warden
gem 'devise', '~> 4.9', '>= 4.9.2'

# CoffeeScript adapter for the Rails asset pipeline.
gem 'coffee-rails', '~> 5.0'

# Upload files in your Ruby applications, map them to a range of ORMs, store them on different backends.
gem 'carrierwave', '~> 3.0', '>= 3.0.2'

# Client library for easily using the Cloudinary service
gem 'cloudinary', '~> 1.27'

# Ffaker generates dummy data.
gem 'ffaker', '~> 2.21'

# Simple authorization solution for Rails. All permissions are stored in a single location.
gem 'cancancan', '~> 3.5'

# RubyCritic is a tool that wraps around various static analysis gems to provide a quality report of your Ruby code.
gem 'rubycritic', '~> 4.8', '>= 4.8.1'

# Very simple Roles library without any authorization enforcement supporting scope on resource objects (instance or class). Supports ActiveRecord and Mongoid ORMs.
gem 'rolify', '~> 6.0', '>= 6.0.1'

# RailsAdmin is a Rails engine that provides an easy-to-use interface for managing your data.
gem 'rails_admin', '~> 3.1', '>= 3.1.2'

# Pry is a runtime developer console and IRB alternative with powerful introspection capabilities
gem 'pry', '~> 0.14.2'

# Turn Pry into a primitive debugger. Adds 'step' and 'next' commands to control execution.
gem 'pry-nav', '~> 1.0'

# Walk the stack in a Pry session
gem 'pry-stack_explorer', '~> 0.6.1'

# Use Pry as your rails console
gem 'pry-rails', '~> 0.3.9'

# Provides a better error page for Rails and other Rack apps
gem 'better_errors', '~> 2.10', '>= 2.10.1'


  
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
