#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e


# --- Functions ---
clean() {
  echo "🧹 Cleaning project artifacts..."
  rm -rf node_modules
  rm -f package-lock.json
  rm -rf .expo
  npm cache clean --force
  echo "✅ Project cleaned successfully."
}

install() {
  echo "📦 Installing dependencies..."
  # npm install
  npm install --legacy-peer-deps && npx expo install --fix -- --legacy-peer-deps
  # npx expo-doctor
  # npx expo install --fix
  # npx expo install --check
  echo "✅ Dependencies installed successfully."
}

# Starts the Expo development server.
start() {
  echo "🚀 Starting the application..."
  npx expo start
}

# Starts the Expo development server with a tunnel.
tunnel() {
  echo "🚇 Starting the application with a tunnel..."
  npx expo start --tunnel
}


# --- Main Logic ---
COMMAND=$1

# Show help if no command is provided.
if [ -z "$COMMAND" ]; then
  echo "A utility script for managing the Expo project."
  echo ""
  echo "Usage: $0 {start|tunnel|clean|install|rebuild}"
  echo "  start   - Starts the Expo development server."
  echo "  tunnel  - Starts the server with a public tunnel URL."
  echo "  clean   - Removes build artifacts and caches (node_modules, etc.)."
  echo "  install - Installs npm dependencies."
  echo "  rebuild - Cleans, reinstalls, and starts the server with a cleared cache and tunnel."
  exit 1
fi

case "$COMMAND" in
  install)
    install
    ;;
  start)
    start
    ;;
  tunnel)
    tunnel
    ;;
  clean)
    clean
    ;;
  rebuild)
    clean
    install
    echo "🚇 Rebuilding and starting the application with a tunnel"
    npx expo start --tunnel --clear
    ;;
  *)
    echo "Error: Unknown command '$COMMAND'"
    exit 1
    ;;
esac

echo "🎉 Done!"
